version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - minio
    environment:
      - S3_ENDPOINT_URL=http://minio:9000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - eira-network

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - eira-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - eira-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    command: server /data --console-address ":9001"
    networks:
      - eira-network

  # Uncomment to add a pgAdmin service for database management
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - eira-network

  # Uncomment to add a worker service for background tasks
  # worker:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   command: celery -A app.worker worker -l info
  #   volumes:
  #     - ./backend:/app
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - redis
  #     - db
  #   networks:
  #     - eira-network

networks:
  eira-network:

volumes:
  postgres_data:
  redis_data:
  minio_data: